### ISSUE TITLE
Font_unicode， this example is super slow，the initialization is about ten seconds

### ISSUE THREAD

**Issue by soastao** [tinyBigGAMES/Luna#5]
font_unicode， this example is super slow，the initialization is about ten seconds

**Comment by jarroddavis68** [comment]
Hi.  That test font is HUGE with an incredibly large number of glyphs and loading from an archive you see this slow down for some reason. Smaller fonts load normally. I will continue to investigate the reason for this.

**Comment by jarroddavis68** [comment]
@soastao just pushed a fix for the slow font loading problem. Should work as expected now. Please let me know. Added a new `TLuBuffer` class. It allows you to allocate large chucks of virtual memory. The `TLuFont.Load` method has a new optional parameter, that if set will use virtual memory and exponentially speeds up operation. This buffer can be used in your projects for all sorts of situations where you need direct access to a large linear buffer of memory. 😎 

Note, be sure to rebuild the Data.arc file because I added new/updated resources.

**Comment by soastao** [comment]
It works well now, very good job

**Comment by jarroddavis68** [comment]
Sweet, glad it's working.
